### ISSUE TITLE
评论回复展示顺序与后端不一致

### ISSUE THREAD

**Issue by LIlGG** [halo-sigs/plugin-comment-widget#13]
## Halo 版本
2.2.0 development

## 插件版本
1.2.0 development

## 问题描述
后端展示的评论回复顺序与插件前端展示的评论顺序不一致。

后端如图所示：
![image](https://user-images.githubusercontent.com/31335418/219543409-cb450779-d54f-4910-a50e-3141b5ae0646.png)

前端如图所示：
![image](https://user-images.githubusercontent.com/31335418/219543487-3b2fcbc4-3f62-4c2e-9433-336af8cdc165.png)

个人认为应该同后端所示，按评论创建时间从上往下正序排列。

/kind bug

**Comment by guqing** [comment]
参考：https://github.com/halo-dev/halo/issues/3330 这应该是 halo 的问题
