### ISSUE TITLE
开启评论需要进行图片静态验证码功能时，评论区未加载验证码图片

### ISSUE THREAD

**Issue by ghost** [halo-sigs/plugin-comment-widget#163]
首次打开页面时的状态
![Image](https://github.com/user-attachments/assets/5e69780c-2a50-42f9-b514-d1d6dd5fafbb)
![Image](https://github.com/user-attachments/assets/9b76cb56-5a02-4f36-a953-16470be9d341)
点击验证码图标后刷新出验证码
![Image](https://github.com/user-attachments/assets/c8cedc58-12a0-4578-b241-1e692e2e3082)

如上图，首次打开时，不显示验证码，需要点击下才可以刷新出来验证码，请帮忙处理下谢谢！

**Comment by ruibaby** [comment]
已经在 2.5.1 修复此问题，稍后更新即可。

https://github.com/halo-dev/plugin-comment-widget/releases/tag/v2.5.1
