### ISSUE TITLE
评论登录状态无法登出

### ISSUE THREAD

**Issue by cetr** [halo-sigs/plugin-comment-widget#2]
点击注销后登录状态一直会显示Anonymous User用户

**Comment by ZHU-SK** [comment]
我也是，而且即便设置了游客可评论（非注册用户可评论），也不会生效，依然需要登陆Anonymous User才能回复评论，以及退出AU账户之后，也必须登陆其他账户才能评论，无法做到非注册用户可评论。谢谢。
