### ISSUE TITLE
无法正常发送评论

### ISSUE THREAD

**Issue by AuroraStarry** [halo-sigs/plugin-comment-widget#21]
halo版本
v2.3.0

评论插件
v1.3.0

问题描述
点击提交评论后，提交按钮一直loading，不回调。去后台发现评论已提交。

**Comment by ruibaby** [comment]
尝试一下清空浏览器缓存，或者打开浏览器开发者工具 Disable cache 试试。

**Comment by AuroraStarry** [comment]
> 尝试一下清空浏览器缓存，或者打开浏览器开发者工具 Disable cache。

清除过cache，disable cache也勾上了，还是一样一直提交评论按钮一直转圈圈。但是数据库里已经有了

**Comment by AuroraStarry** [comment]
在最新的`halo2.3.1`已经正常发送评论
