### ISSUE TITLE
希望所有评论可以默认展开

### ISSUE THREAD

**Issue by laffitto** [halo-sigs/plugin-comment-widget#22]
如果评论再有回复，现在默认是需要再点一下的，希望能够默认评论全部展开或者加个开关之类的。另外希望评论显示时间是具体的时间而不是相对于现在的时间~
![image](https://user-images.githubusercontent.com/52039038/222960579-6cff28b6-8e40-4815-a4d3-67a9be5eb3f9.png)

**Comment by ruibaby** [comment]
目前评论回复是异步获取的，并且回复和评论属于不同的模型。所以如果要默认全部展开，带来的资源消耗可能比较大。

时间格式问题请看：https://github.com/halo-sigs/plugin-comment-widget/issues/18
