### ISSUE TITLE
评论回复在前端无法显示

### ISSUE THREAD

**Issue by cetr** [halo-sigs/plugin-comment-widget#3]
回复在console已审核，但在文章里不显示，但能看到有一条回复

![image](https://user-images.githubusercontent.com/49756728/205667032-f7ff57b8-532b-4df0-8859-9c4d9136f2d4.png)

**Comment by guqing** [comment]
通过 GET /apis/api.console.halo.run/v1alpha1/replies 看看没显示出来那条回复是什么样的 json 贴出来看一下

**Comment by cetr** [comment]
> 通过 GET /apis/api.console.halo.run/v1alpha1/replies 看看没显示出来那条回复是什么样的 json 贴出来看一下，以及当前这条评论的 json

{"page":0,"size":0,"total":1,"items":[{"reply":{"spec":{"raw":"回复测试","content":"回复测试","owner":{"kind":"User","name":"anonymousUser","displayName":"Anonymous User"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","ipAddress":"1.84.27.72","approvedTime":"2022-12-04T13:45:12.739Z","priority":0,"top":false,"allowNotification":true,"approved":true,"hidden":true,"commentName":"74231480-4290-4403-a41f-58e9e67e2bf0"},"apiVersion":"content.halo.run/v1alpha1","kind":"Reply","metadata":{"name":"c09ad889-70f2-4160-b083-cfd31a710f30","version":1,"creationTimestamp":"2022-12-04T13:44:01.981451241Z"}},"owner":{"kind":"User","name":"anonymousUser","displayName":"Anonymous User","email":"anonymous@example.com"}}],"first":true,"last":true,"hasNext":false,"hasPrevious":false,"totalPages":1}

**Comment by cetr** [comment]
> 通过 GET /apis/api.console.halo.run/v1alpha1/replies 看看没显示出来那条回复是什么样的 json 贴出来看一下，以及当前这条评论的 json

{"page":0,"size":0,"total":0,"items":[],"first":true,"last":true,"hasNext":false,"hasPrevious":false,"totalPages":1}

**Comment by xyhcode** [comment]
我也发现了这个问题 无法查看回复内容 后台已通过审核，前台依旧显示没有回复内容

**Comment by guqing** [comment]
> > 通过 GET /apis/api.console.halo.run/v1alpha1/replies 看看没显示出来那条回复是什么样的 json 贴出来看一下，以及当前这条评论的 json
> 
> 
> 
> ```json
> 
> {
> 
>    "page":0,
> 
>    "size":0,
> 
>    "total":0,
> 
>    "items":[
> 
>       
> 
>    ],
> 
>    "first":true,
> 
>    "last":true,
> 
>    "hasNext":false,
> 
>    "hasPrevious":false,
> 
>    "totalPages":1
> 
> }
> 
> ```
不显示是因为 "hidden":true 目前并未发现是因为什么导致 hidden 为 true

**Comment by xyhcode** [comment]
@guqing 我已找问题：当开启审核评论后 用户评论之后在后台审核通过时 就会出现无法显示的情况，反之把关闭审核功能就不会有这个问题 所以应该是审核导致的

**Comment by guqing** [comment]
> @guqing 我已找问题：当开启审核评论后 用户评论之后在后台审核通过时 就会出现无法显示的情况，反之把关闭审核功能就不会有这个问题 所以应该是审核导致的

已成功复现是回复的问题，之前改的只改了评论忘记改回复了，你可以转到 Halo 提一个 issue ，如果你愿意修复这个它的话也非常欢迎：
只需要将 `run.halo.app.content.comment.ReplyServiceImpl`  的 `reply.getSpec().setHidden(!reply.getSpec().getApproved());` 修改为初始值 false 即可

https://github.com/halo-dev/halo/blob/7a2f5d0a99575e70942dac7a13600650a2ae2b1f/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java#L65

**Comment by xyhcode** [comment]
> > @guqing 我已找问题：当开启审核评论后 用户评论之后在后台审核通过时 就会出现无法显示的情况，反之把关闭审核功能就不会有这个问题 所以应该是审核导致的
> 
> 已成功复现，是回复的问题，之前改的只改了评论忘记改回复了，你可以转到 Halo 提一个 issue ，如果你愿意修复它的话也非常欢迎： 只需要将 `run.halo.app.content.comment.ReplyServiceImpl` 的 `reply.getSpec().setHidden(!reply.getSpec().getApproved());` 修改为初始值 false 即可
> 
> https://github.com/halo-dev/halo/blob/7a2f5d0a99575e70942dac7a13600650a2ae2b1f/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java#L65

刚开始使用halo，修改还是各位大佬修改

**Comment by guqing** [comment]
此问题已在 https://github.com/halo-dev/halo/pull/2954 修复，因此先关闭此 issue，如果有问题随时 reopen
