### ISSUE TITLE
插件初始化失败

### ISSUE THREAD

**Issue by dllcnx** [halo-sigs/plugin-comment-widget#52]
我第一次访问有评论插件的页面的时候会报错CommentWidget is not defined，再次刷新页面或者点击页面，又会正常渲染，不知道是主题问题还是插件问题。

**Comment by ruibaby** [comment]
哪个主题

**Comment by dllcnx** [comment]
> 哪个主题

hao这个主题，最新版本主题已经解决了这个问题。
