### ISSUE TITLE
请求提供原始js文件

### ISSUE THREAD

**Issue by nasheep** [halo-sigs/plugin-comment-widget#57]
请问源码中的comment-widget.iife.js文件为什么是压缩格式的？可以提供原始的js文件吗？谢谢。

**Comment by guqing** [comment]
iife 格式参考：https://developer.mozilla.org/en-US/docs/Glossary/IIFE
它是由源码 https://github.com/halo-sigs/plugin-comment-widget/tree/main/packages/comment-widget/src 经 vite 打包后的产物

/kind support

**Comment by nasheep** [comment]
> iife 格式参考：https://developer.mozilla.org/en-US/docs/Glossary/IIFE 它是由源码 https://github.com/halo-sigs/plugin-comment-widget/tree/main/packages/comment-widget/src 经 vite 打包后的产物
> 
> /kind support

原来如此，感谢您的回复
