### ISSUE TITLE
无法注册

### ISSUE THREAD

**Issue by xyhcode** [halo-sigs/plugin-comment-widget#6]
用户无法注册  全是一样的名字 一样的头像 
<img width="793" alt="image" src="https://user-images.githubusercontent.com/64968400/209463742-6808c3af-207e-4972-b128-18df20e6d5f6.png">

**Comment by ZHU-SK** [comment]
我也是遇到一样的问题。。

**Comment by ruibaby** [comment]
已经在 #9 中解决无法退出的问题，注册请关注：https://github.com/halo-dev/halo/issues/2813

/close
